// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// LCS
List LCS(DataFrame order_1, DataFrame order_2);
RcppExport SEXP LCSLCIS_LCS(SEXP order_1SEXP, SEXP order_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type order_1(order_1SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type order_2(order_2SEXP);
    __result = Rcpp::wrap(LCS(order_1, order_2));
    return __result;
END_RCPP
}
// LCIS
List LCIS(DataFrame order_1, DataFrame order_2);
RcppExport SEXP LCSLCIS_LCIS(SEXP order_1SEXP, SEXP order_2SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< DataFrame >::type order_1(order_1SEXP);
    Rcpp::traits::input_parameter< DataFrame >::type order_2(order_2SEXP);
    __result = Rcpp::wrap(LCIS(order_1, order_2));
    return __result;
END_RCPP
}
