# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LCS <- function(order_1, order_2) {
    .Call('LCSLCIS_LCS', PACKAGE = 'LCSLCIS', order_1, order_2)
}

LCIS <- function(order_1, order_2) {
    .Call('LCSLCIS_LCIS', PACKAGE = 'LCSLCIS', order_1, order_2)
}

